chore: update gem to v2.1.0 and setup krystal forked version
krystal/nominet-epp pull request #1
Opened 2023-03-30 15:41 UTC by rdsngit

This starts the krystal fork of the `nominet-epp` gem. 

- Named it `krystal-nominet-epp` to avoid name clashes with the original gem
- Bumped the gem's version to 3.0.0 because we have upped the minimum ruby version requirement from v2.0 to v2.7.
- Updated the gemspec to a similar approach to the identity gemspec: https://github.com/krystal/krystal-identity-ruby-client/blob/main/krystal-identity.gemspec
- Added a workflow CI file is based on the one we use for apia: https://github.com/krystal/apia/blob/main/.github/workflows/ci.yml#L22

2023-03-30 15:52 UTC, andrewjtait requested changes
I'd have a go at adding a GitHub workflow file, even if it is just to run the tests for now. I don't know if the changes you've made still pass the test suite?

2023-03-30 15:52 UTC, andrewjtait commented on .rubocop.yml
> +AllCops:
How about inheriting from `https://dev.k.io/rubocop/rubocop.yml`?

2023-03-30 15:58 UTC, rdsngit commented
> I'd have a go at adding a GitHub workflow file, even if it is just to run the tests for now. I don't know if the changes you've made still pass the test suite?

The tests will need some work to update - the run with minitest at the moment

2023-03-30 16:03 UTC, rdsngit commented
@andrewjtait I've added the commit workflow file, but there's so many rubocop fixes to make I didn't think that was a good idea for the initial gem setup branch. I'm happy to fix those in another branch as it will probably be a lot of changes.

2023-03-30 16:20 UTC, andrewjtait requested changes
> The tests will need some work to update - they run with minitest at the moment so if we want to use rspec it will involve installing that and changing most if not all the test files

I wouldn't bother re-writing it to use rspec, let's just stick with minitest for this repo.

> I've added the commit workflow file, but there's so many rubocop fixes to make I didn't think that was a good idea for the initial gem setup branch. I'm happy to fix those in another branch as it will probably be a lot of changes.

Ah yeah, most of them are auto fixable though which is good.

---

For this first branch, let's get the workflow setup to run the tests. It's an important first step as it will ensure we can find any changes that break anything.

As for the Rubocop stuff, I'm unsure on the best course of action... it might be worth _not_ setting Rubocop up, so that we can more easily see changes that divert from the original repo. If we add and fix the Rubocop changes then it becomes a lot more difficult to see what changes we've made.

If we don't care about this, then I'd disable the Rubocop workflow for now. Then you can fix all the errors and turn it on in a subsequent PR - in fact it might make sense just to do all of the Rubocop stuff in a separate change.

2023-03-30 16:20 UTC, andrewjtait commented on .rubocop-https---dev-k-io-rubocop-rubocop-yml
> +AllCops:
This file will need adding to a gitignore.

2023-03-30 16:20 UTC, andrewjtait commented on .rubocop.yml
> +  EnforcedStyle: brackets
There are a bunch of rules in here that are now duplicates of the ones from dev.k.io, you should remove any duplicates.

2023-03-30 16:31 UTC, rdsngit commented on .rubocop.yml
> +  EnforcedStyle: brackets
[16b1aaa](https://github.com/krystal/nominet-epp/pull/1/commits/16b1aaa9addf35d2b0566c4127f5455123b94efe) - removed inherited rules here

2023-03-30 16:36 UTC, jimeh commented on Gemfile
>  end
Since we're changing stuff, might as well move development dependencies to the gemspec?

2023-03-30 16:36 UTC, jimeh commented on Gemfile.lock
We probably shouldn't include a lock file in the repo. As it will be ignored by apps that use the gem anyway.

2023-03-30 16:41 UTC, jimeh commented on .github/workflows/commit.yml
Nitpick: Conventionally we tend to use a single workflow called `CI` / `ci.yml`, as we'll have various jobs that depend on each other. And potentially trigger some parts on push, and some on PR events.

2023-03-30 16:43 UTC, jimeh commented
We could mark all current rubocop complaints as todos with the `--auto-gen-config` flag and commit the todo file.

2023-03-30 16:45 UTC, andrewjtait commented
@jimeh what's your opinion on this:

> it might be worth not setting Rubocop up, so that we can more easily see changes that divert from the original repo.

2023-03-30 16:46 UTC, rdsngit commented on test/test_nominet-epp.rb
> +require_relative './helper'
[f201270](https://github.com/krystal/nominet-epp/pull/1/commits/f201270051ccfa8326e5480d4a8ca06244c13a35) - yeah, I had added that when I was initially trying to get the tests to run, using `rake test` doesn't need the require relative

2023-03-30 16:47 UTC, rdsngit commented
It's a good point to not add rubocop yet, and do that in another branch

2023-03-30 16:49 UTC, rdsngit commented on .github/workflows/commit.yml
[4ddcfbe](https://github.com/krystal/nominet-epp/pull/1/commits/4ddcfbe27940de47b5e7174541c4208e462c673d) - happy to do that if this is the way we are naming it now

2023-03-30 16:50 UTC, andrewjtait commented
> I just left a comment suggesting we use a todo file for all current complaints. As it means new code will for the most part have to comply with rubocop rules.

@jimeh Yeah that's a good point so we can use them for new code, but in general do you think we should avoid fixing the "pending" complaints? Otherwise I don't think it'd take long to fix them all.

2023-03-30 16:51 UTC, rdsngit commented on Gemfile.lock
[6e25d86](https://github.com/krystal/nominet-epp/pull/1/commits/6e25d862aa4abf1becd56c766a9e362c5900aa01) - have removed the lockfile here and added it to the .gitignore

2023-03-30 16:55 UTC, jimeh commented
@andrewjtait I assume we're basically doing a hard fork and not really caring about minimizing the diff size should we submit a PR to the upstream, right? If so we should go ahead and fix all linting issues bringing code quality and style in-line with what we prefer.

That does not have to all happen right away though, and we can start with a todo file here to minimize changes, get a working CI workflow confirming correct behavior. Then separately take a big stab at the rubocop todo file in a new PR.

2023-03-30 16:58 UTC, rdsngit commented on Gemfile
>  end
I've removed rubocop now so that we can focus on getting this branch setup and can add it in another branch.

2023-03-30 16:59 UTC, andrewjtait commented
> I assume we're basically doing a hard fork and not really caring about minimizing the diff size should we submit a PR to the upstream, right?

I wasn't necessarily thinking we'd contribute back, but more along the lines of if they ever push some updates that we'd like to pull. That said, they haven't updated in 8 years(?) - so probably best not to expect much 😅 

> That does not have to all happen right away though, and we can start with a todo file here to minimize changes, get a working CI workflow confirming correct behavior. Then separately take a big stab at the rubocop todo file in a new PR.

Agreed. But happy for all the Rubocop stuff to just go in one separate PR, if that's easier.

2023-03-30 17:01 UTC, paulsturgess commented
+1 for getting the gem up and running with as few changes as possible for now. and then making our own tweaks. It will give us a clearer "line in the sand" to see what we inherited vs what we since changed.

2023-03-30 17:03 UTC, rdsngit commented
FYI I'm focusing on getting the workflow file running properly so the tests can run. I have a feeling that the tests will pass about 93%, which is what it says when I run `rake test` locally.

2023-03-31 08:26 UTC, rdsngit commented
@jimeh I'm leaving a copy of some of out discussion about the workflow file on the pr so others can see the context:

Me: I had a go but it errors with rake not found. It could be a bit of a rabbit hole because the gem was made using ruby versions 1.8 - 2.0 and now we are on 3.1.3. Plus I'm not sure if the tests were passing 100% after the last change in the original repo for the gem.

Jim: 

Right, you need to add rake as a development dependency, it used to be include with Ruby a long long time ago, but not anymore…

Ah, the bundle without “default” would cause rake to be excluded…

I’d say move all deps out of the Gemfile to the gemspec, as dev deps, with an exception of the git dependency… as that can’t be done with the gemspec…

Then a regular bundle install should really be enough setup

As for caching gems, let’s skip the manual vendor path setup stuff, and just use the example from the cache action: 

https://github.com/actions/cache/blob/master/examples.md#ruby---bundler
[18:16](https://krystopia.slack.com/archives/D041A4MAHAQ/p1680196612628669)

```yml
uses: ruby/setup-ruby@v1
  with:
    ruby-version: ...
    bundler-cache: true
```

Might be an idea to try it with a few versions using a matrix too, tests in our apia gem serve as a decent example:

https://github.com/krystal/apia/blob/main/.github/workflows/ci.yml#L22

2023-03-31 08:28 UTC, rdsngit commented
The nominet-epp gem depends on the epp-client gem, which also hasn't been maintained for a long time.

In the nominet-epp Gemfile there is currently:

gem 'epp-client', :github => "m247/epp-client"

I had suggested we fork that as well when we were discussing the idea of forking the nominet-epp gem.

@jimeh agreeds: "I think we might need to fork that repo too and release it as a Krystal variant gem, otherwise any apps that uses the our nominet gem needs to include the same git ref…"

2023-03-31 09:02 UTC, jimeh commented on nominet-epp.gemspec
> +  gem.name          = "nominet-epp"
Do we want to change the gem name to `Krystal-nominet-epp` maybe to avoid naming conflicts with the original?

2023-03-31 09:17 UTC, rdsngit commented
Update: between me and @jimeh we managed to add the dependent gems, require lines, and update the ci workflow so that the test job now passes on github actions 🎉

2023-03-31 09:26 UTC, rdsngit commented on nominet-epp.gemspec
> +  gem.name          = "nominet-epp"
[4a92b7d](https://github.com/krystal/nominet-epp/pull/1/commits/4a92b7d5df6fec37409df936b9adb6db934e0b18) - changed the name in the gemspec and also the title in the readme to use Krystal Nominet EPP

2023-03-31 09:31 UTC, rdsngit commented on nominet-epp.gemspec
> +  gem.name          = "nominet-epp"
[5e7ec04](https://github.com/krystal/nominet-epp/pull/1/commits/5e7ec0403a79c28b7534c3046d6126973d56d7df) - updated the name of the gem to krystal-nominet-epp in the example code in the readme

2023-03-31 09:52 UTC, rdsngit commented
@jimeh FYI I've put a few related tasks in a list on the ticket rather than this pr, like using a git tag for this new version of the gem https://github.com/krystal/domains/issues/367

2023-03-31 09:57 UTC, andrewjtait approved these changes

2023-03-31 11:16 UTC, mattbearman commented on Gemfile
>  gem 'epp-client', :github => "m247/epp-client"
`epp-client` is hosted on ruby gems, so we shouldn't need to specify the GitHub source - https://rubygems.org/gems/epp-client

2023-03-31 11:17 UTC, rdsngit commented on Gemfile
>  gem 'epp-client', :github => "m247/epp-client"
will try this out

2023-03-31 11:21 UTC, rdsngit commented on Gemfile
>  gem 'epp-client', :github => "m247/epp-client"
[1bad330](https://github.com/krystal/nominet-epp/pull/1/commits/1bad330c520f2730dd89c3444a18481d8e18f72f) - nice call Matt! it all works fine without that github referenced line in the gemfile

@jimeh this addresses your comment about the github ref in the gemfile

2023-03-31 13:04 UTC, rdsngit commented
Closing the PR as we decided to start the repo again.

2023-03-31 13:04 UTC, closed without merging